/*
 * MeMaS CP APIs
 * This is the Control Plane APIs for MeMaS (Memory Management Service).
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: max.yu@memas.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.memas.memas_sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Type of a Corpus
 */
@JsonAdapter(CorpusType.Adapter.class)
public enum CorpusType {
  
  KNOWLEDGE("knowledge"),
  
  CONVERSATION("conversation");

  private String value;

  CorpusType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static CorpusType fromValue(String value) {
    for (CorpusType b : CorpusType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<CorpusType> {
    @Override
    public void write(final JsonWriter jsonWriter, final CorpusType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public CorpusType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return CorpusType.fromValue(value);
    }
  }
}

