/*
 * MeMaS APIs
 * This is the Control Plane and Data Plane APIs for MeMaS (Memory Management Service). See https://github.com/memas-ai/MeMaS for more details.
 *
 * The version of the OpenAPI document: 0.1.1
 * Contact: max.yu@memas.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.memas.memassdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for DeleteCorpusRequest
 */
public class DeleteCorpusRequestTest {
    private final DeleteCorpusRequest model = new DeleteCorpusRequest();

    /**
     * Model tests for DeleteCorpusRequest
     */
    @Test
    public void testDeleteCorpusRequest() {
        // TODO: test DeleteCorpusRequest
    }

    /**
     * Test the property 'namespacePathname'
     */
    @Test
    public void namespacePathnameTest() {
        // TODO: test namespacePathname
    }

    /**
     * Test the property 'corpusPathname'
     */
    @Test
    public void corpusPathnameTest() {
        // TODO: test corpusPathname
    }

}
