/*
 * MeMaS CP APIs
 * This is the Control Plane APIs for MeMaS (Memory Management Service).
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: max.yu@memas.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.memas.memas_sdk.model;

import com.google.gson.annotations.SerializedName;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CorpusType
 */
public class CorpusTypeTest {
    /**
     * Model tests for CorpusType
     */
    @Test
    public void testCorpusType() {
        // TODO: test CorpusType
    }

}
