/*
 * MeMaS CP APIs
 * This is the Control Plane APIs for MeMaS (Memory Management Service).
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: max.yu@memas.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.memas.memas_sdk.model;

import ai.memas.memas_sdk.model.CorpusType;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CreateCorpusRequest
 */
public class CreateCorpusRequestTest {
    private final CreateCorpusRequest model = new CreateCorpusRequest();

    /**
     * Model tests for CreateCorpusRequest
     */
    @Test
    public void testCreateCorpusRequest() {
        // TODO: test CreateCorpusRequest
    }

    /**
     * Test the property 'corpusPathname'
     */
    @Test
    public void corpusPathnameTest() {
        // TODO: test corpusPathname
    }

    /**
     * Test the property 'corpusType'
     */
    @Test
    public void corpusTypeTest() {
        // TODO: test corpusType
    }

}
