/*
 * MeMaS APIs
 * This is the Control Plane and Data Plane APIs for MeMaS (Memory Management Service). See https://github.com/memas-ai/MeMaS for more details.
 *
 * The version of the OpenAPI document: 0.1.1
 * Contact: max.yu@memas.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.memas.memassdk.api;

import ai.memas.memassdk.invoker.ApiCallback;
import ai.memas.memassdk.invoker.ApiClient;
import ai.memas.memassdk.invoker.ApiException;
import ai.memas.memassdk.invoker.ApiResponse;
import ai.memas.memassdk.invoker.Configuration;
import ai.memas.memassdk.invoker.Pair;
import ai.memas.memassdk.invoker.ProgressRequestBody;
import ai.memas.memassdk.invoker.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import ai.memas.memassdk.model.CitedDocument;
import ai.memas.memassdk.model.Memorize200Response;
import ai.memas.memassdk.model.Memorize400Response;
import ai.memas.memassdk.model.MemorizeRequest;
import ai.memas.memassdk.model.RecallRequest;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.ws.rs.core.GenericType;

public class DpApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public DpApi() {
        this(Configuration.getDefaultApiClient());
    }

    public DpApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for memorize
     * @param memorizeRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Operation </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Failed operation </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call memorizeCall(MemorizeRequest memorizeRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = memorizeRequest;

        // create path and map variables
        String localVarPath = "/dp/memorize";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call memorizeValidateBeforeCall(MemorizeRequest memorizeRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'memorizeRequest' is set
        if (memorizeRequest == null) {
            throw new ApiException("Missing the required parameter 'memorizeRequest' when calling memorize(Async)");
        }

        return memorizeCall(memorizeRequest, _callback);

    }

    /**
     * Memorize information
     * Memorize information
     * @param memorizeRequest  (required)
     * @return Memorize200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Operation </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Failed operation </td><td>  -  </td></tr>
     </table>
     */
    public Memorize200Response memorize(MemorizeRequest memorizeRequest) throws ApiException {
        ApiResponse<Memorize200Response> localVarResp = memorizeWithHttpInfo(memorizeRequest);
        return localVarResp.getData();
    }

    /**
     * Memorize information
     * Memorize information
     * @param memorizeRequest  (required)
     * @return ApiResponse&lt;Memorize200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Operation </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Failed operation </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Memorize200Response> memorizeWithHttpInfo(MemorizeRequest memorizeRequest) throws ApiException {
        okhttp3.Call localVarCall = memorizeValidateBeforeCall(memorizeRequest, null);
        Type localVarReturnType = new TypeToken<Memorize200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Memorize information (asynchronously)
     * Memorize information
     * @param memorizeRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Operation </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Failed operation </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call memorizeAsync(MemorizeRequest memorizeRequest, final ApiCallback<Memorize200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = memorizeValidateBeforeCall(memorizeRequest, _callback);
        Type localVarReturnType = new TypeToken<Memorize200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for recall
     * @param recallRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> successful operation </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Failed operation </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call recallCall(RecallRequest recallRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = recallRequest;

        // create path and map variables
        String localVarPath = "/dp/recall";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call recallValidateBeforeCall(RecallRequest recallRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'recallRequest' is set
        if (recallRequest == null) {
            throw new ApiException("Missing the required parameter 'recallRequest' when calling recall(Async)");
        }

        return recallCall(recallRequest, _callback);

    }

    /**
     * Recalls information
     * Recalls relevant information related to the given clue
     * @param recallRequest  (required)
     * @return List&lt;CitedDocument&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> successful operation </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Failed operation </td><td>  -  </td></tr>
     </table>
     */
    public List<CitedDocument> recall(RecallRequest recallRequest) throws ApiException {
        ApiResponse<List<CitedDocument>> localVarResp = recallWithHttpInfo(recallRequest);
        return localVarResp.getData();
    }

    /**
     * Recalls information
     * Recalls relevant information related to the given clue
     * @param recallRequest  (required)
     * @return ApiResponse&lt;List&lt;CitedDocument&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> successful operation </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Failed operation </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<List<CitedDocument>> recallWithHttpInfo(RecallRequest recallRequest) throws ApiException {
        okhttp3.Call localVarCall = recallValidateBeforeCall(recallRequest, null);
        Type localVarReturnType = new TypeToken<List<CitedDocument>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Recalls information (asynchronously)
     * Recalls relevant information related to the given clue
     * @param recallRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> successful operation </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Failed operation </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call recallAsync(RecallRequest recallRequest, final ApiCallback<List<CitedDocument>> _callback) throws ApiException {

        okhttp3.Call localVarCall = recallValidateBeforeCall(recallRequest, _callback);
        Type localVarReturnType = new TypeToken<List<CitedDocument>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
